### ISSUE TITLE
Fortain pen and Mamemomi statement 6 in episode 1

### ISSUE THREAD

**Issue by RandomMicrowave** [ScarletStudy/DGS2-3DS-Release#16] opened 2021-10-02 19:21 UTC
At episode 1 
Citra Nightly 8 Gb ram Intel core i5 4570
Examining the Fontain pen freezes the screen in the emulator window but the game keeps running. You can "fix" this if you save state after ending ur examining restarting the game and loading the state back the problem is even after you point the part you need to examine in order to update the fortain pen the part of Mamemomi testimony the statement 6 you need to present the pen and when you it threats as a wrong one making you not being able to progress the game

**Comment by wabberz** [comment] 2021-10-02 20:51
Not easy parsing your issue, but it seems to be a duplicate of issue #10, which is a bug in the original game. If it still persists in the latest version (not used in our patch), we may or may not be able to fix it.

In any case, we only take bug reports from real hardware, since it's impossible for us to determine whether or not the emulator is the reason for the bug.

**Closed as completed by wabberz** 2021-10-02 20:51 UTC
Labels: bug, duplicate, engine bug

**Comment by RandomMicrowave** [comment] 2021-10-16 22:16
i think it was my GPU i took something from this post https://community.citra-emu.org/t/my-screen-freezes-but-i-can-hear-the-game-continue/251406 and apparenly i needed some kind of "AMD hack" and it worked in that nightly-860 version there was not screen freeze at examining the pen anymore the only problem being not able to patch but you can just save the game and return to the normal citra. This just to clarify more the situation as may not be a bug from the game
